function sigDEN = func_denoise_db4_level4(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 31-Oct-2017 03:05:21

% Analysis parameters.
%---------------------
wname = 'db4';
level = 4;

% Denoising parameters.
%----------------------
% meth = 'sqtwolog';
% scal_or_alfa = mln;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    0.429024842063934 ; ...
    0.284241142542337 ; ...
    0.420700998959027 ; ...
    0.494529419331006 ; ...
    0.219553070709912   ...
    ];

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
