function sigDEN = func_denoise_dwsym(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 31-Oct-2017 02:33:50

% Analysis parameters.
%---------------------
wname = 'sym6';
level = 5;

% Denoising parameters.
%----------------------
% meth = 'sqtwolog';
% scal_or_alfa = mln;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    0.439159072647418 ; ...
    0.255540506666587 ; ...
    0.466971462422052 ; ...
    0.392816953541544 ; ...
    0.203993463392230   ...
    ];

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
