function [fitresult, gof] = createFit(ALL_TIME, ALL_TRAIN)
%CREATEFIT1(ALL_TIME,ALL_TRAIN)
%  Create a fit.
%
%  Data for 'fit2' fit:
%      X Input : ALL_TIME
%      Y Output: ALL_TRAIN
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Nov-2017 02:34:11


%% Fit: 'fit2'.
[xData, yData] = prepareCurveData( ALL_TIME, ALL_TRAIN );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Create a figure for the plots.
figure( 'Name', 'fit2' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'ALL_TRAIN vs. ALL_TIME', 'fit2', 'Location', 'NorthEast' );
% Label axes
xlabel ALL_TIME
ylabel ALL_TRAIN
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'fit2 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel ALL_TIME
ylabel ALL_TRAIN
grid on


